version: '3'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: sm_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sm-network

  redis:
    container_name: sm_redis
    image: redis:7.2.3
    ports:
      - "6379:6379"
    networks:
      - sm-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.19
    container_name: sm_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/homebrew/var/www/html/magento/docker/elasticsearch-data:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: sm_kibana
    image: docker.elastic.co/kibana/kibana:7.17.19
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:8.0
    container_name: sm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root_password}"
      MYSQL_DATABASE: "${DB_DATABASE:-magento}"
      MYSQL_USER: "${DB_USERNAME:-user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sm-network

  phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: sm_phpmyadmin
    ports:
      - 8081:80
    networks:
      - sm-network
    environment:
      PMA_ARBITRARY: "${PMA_ARBITRARY:-1}"
      UPLOAD_LIMIT: "${UPLOAD_LIMIT:-500M}"
      PMA_HOST: "${DB_HOST:-mysql}"
      PMA_USER: "${DB_USERNAME:-user}"
      PMA_PASSWORD: "${DB_PASSWORD:-password}"

volumes:
  elasticsearch-data:
    driver: local
  mysql-data:
    driver: local

networks:
  sm-network:
    driver: bridge
  stack: {}
